#!/usr/bin/env bash

set -o pipefail

if git rev-parse --verify HEAD >/dev/null 2>&1; then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

exit_val=0

check_whitespace() {
	# If there are whitespace errors, print the offending file names and fail.
	if ! git diff-index --check --cached ${against} --; then
		echo "Error: files have whitespace errors"
		exit_val=1
	fi
}

check_clang_format() {
	local f
	local fail=0
	local files=$(git diff --cached --name-only \
		| grep -E '\.(c|cpp|h|hpp)$')

	local fails=()
	for f in ${files}; do
		[ ! -s "${f}" ] && continue
		# Note: only the .clang-format in the top dir is used
		if ! git show ":${f}" \
				| clang-format -assume-filename="${f}" -style=file \
				| cmp -s <(git show ":${f}") -
		then
			fails=("${fails[@]}" "${f}")
			fail=1
		fi
	done

	if [ ${fail} -ne 0 ]; then
		echo "Error: files not clang-formatted"
		printf "  %s\n" "${fails[@]}"
		exit_val=1
	fi
}

check_whitespace
check_clang_format

exit ${exit_val}

# vim: noet
